# Generated by Django 5.1.4 on 2025-01-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
