# Generated by Django 5.1.4 on 2025-01-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_gymcard_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymcard',
            name='status',
            field=models.TextField(default=True),
        ),
    ]
