# Generated by Django 5.1.4 on 2025-01-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_gymcard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymcard',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
