# Generated by Django 5.1.4 on 2025-01-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_gymcard_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymcard',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('deactivated', 'Deactivated'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
    ]
