# Generated by Django 5.1.5 on 2025-01-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_gymcard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymcard',
            name='rfid_card_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
